spring.application.name=cuentas
spring.profiles.default=local
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:DB-cuentas}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
